### ISSUE TITLE
Polymer notification fails on some props 

### ISSUE THREAD

**Issue by alshakero** [Starcounter/starcounter-include#52] opened 2017-09-01 11:16 UTC
To reproduce fellow this clear enough steps https://github.com/StarcounterApps/Calendar/pull/81#issuecomment-326291207

I fixed it by adding:
```js
this.template._notifyPath(
    path.replace("partial.", "model.")
         .replace("viewModel.", "model."),
         value);
```
After line **263**.

https://github.com/Starcounter/starcounter-include/blob/cad18584843a894b0bd3144a804d0623d55e22b5/starcounter-include.html#L246-L264

I didn't PR because this doesn't seem very clean and is potentially incorrect, but it does fix the problem. That's why I'd appreciate your input @tomalec.

**Comment by tomalec** [comment] 2017-09-01 12:00
This is actually not working by design see https://github.com/Starcounter/starcounter-include/issues/29.

Calendar should either use `Self.GET` and `<starcounter-include>` or `<tempalte is="imported-template">` if it does not use blending point (`Self.GET` => namespaces => place for Shadow DOM compositions, other apps' responses, etc.)

**Comment by alshakero** [comment] 2017-09-01 12:18
Ah cool. @PatrykSzwer could you check this ^

**Comment by joozek78** [comment] 2017-09-01 12:18
If I understand this correctly, this will mean that you can't create wrappers (like [this](https://github.com/StarcounterApps/Calendar/blob/77012f75265982362141741a2c0646d0958bb665/src/Calendar/wwwroot/Calendar/viewmodels/launcher/MasterPage.html)) - am I correct? Please note that I can't use `Self.GET` in this case, as I want to wrap an already existing page (`Json`).
If that's the case I find it very limiting. I'm also sorry that I've missed my opportunity to opine about #29

**Comment by tomalec** [comment] 2017-09-01 13:13
Could you elaborate more on "wrappers" and link server-side code as well?
Is `CurrentPage` meant to be blending point? - contain responses from many apps, composition's etc?
 - if is you **need** to use `Self.GET` otherwise you will not get a merged result.
 - if not, and you deliberately don't want Starcounter features, use `imported-template`. For example `<template is="imported-template" model="{{model.CurrentPage}}" content$="{{model.CurrentPage.Html}}">`.

Simply:> If you want to make it Starcounter's blending point, use insertion point on client and server.  If you don't want to use blending, don't use it. And for sure don't try to pretend you are using it on the client while you are not supporting it on the server.

**Comment by tomalec** [comment] 2017-09-01 13:14
BTW, how such "wrapper" differs from any other regular (blendable) view, that nests another (blendable one)?

**Comment by joozek78** [comment] 2017-09-01 13:34
> Could you elaborate more on "wrappers" and link server-side code as well?

Take a look [here](https://github.com/StarcounterApps/Calendar/blob/ef3670a70834c0edb4b087982dcc3ca2e7f4d26a/src/Calendar/Api/Routing/MasterPageMiddleware.cs#L12)
```c#
// next() returns original Json that gets wrapped here
// by design we don't have its URI at this point (it's not guaranteed it even has one)
return SessionHelper.GetMaster(() => next());
```

> Is CurrentPage meant to be blending point? - contain responses from many apps, composition's etc?

No, it's meant only to contain one `Json`, inserted by server-side code

> if not, and you deliberately don't want Starcounter features, use imported-template. For example <template is="imported-template" model="{{model.CurrentPage}}" content$="{{model.CurrentPage.Html}}">.

That looks like it should work, but it's obviously less than convenient. If there are numerous reasons, then I have no problem accepting it, but I'm afraid that maybe no one thought about wrappers (or similar) use case when deciding to drop the support.

**Comment by tomalec** [comment] 2017-09-01 13:47
> `// next() returns original Json that gets wrapped here`

What gets wrapped here? Sorry, I still don't get a clear picture how and why it's built like so.

> That looks like it should work, but it's obviously less than convenient.

What do you find less convenient?

In fact, we did think and talked about wrappers a lot. We just thought the only "wrapper" that does not wrap blending point, was the root one (which was fixed recently https://github.com/Starcounter/Announcements/issues/26, https://github.com/Starcounter/Announcements/issues/33

**Comment by tomalec** [comment] 2017-09-01 13:49
Maybe you could start a separate discussion on rebels lounge on wrappers if you need the support of a particular case we missed.

I believe it's also something to discuss for App Architecture TF
//cc @warpech

**Comment by tomalec** [comment] 2017-09-01 13:52
BTW, please note that even previously it was not working in 100%, as you were not able to save and receive a custom Shadow DOM layout Composition (via CompositionProvider app) for such wrapped partial view.

**Comment by alshakero** [comment] 2017-09-12 16:02
@bouguila has just reported that updating the array isn't updating the `dom-repeat` for him. And this happens exactly in build 7023 http://teamcity.starcounter.org/viewLog.html?buildId=29942&tab=buildResultsDiv&buildTypeId=Starcounter_V23NightlyWindows where `starcounter-include` was updated to 3.0.0.

I have a doubt that it might be the same issue as this. Could you please check it?

Here is the code: https://github.com/StarcounterApps/People/blob/develop/src/People/wwwroot/People/viewmodels/TagsPage.html#L9

**Comment by tomalec** [comment] 2017-09-12 18:24
Once again it's non-namespaced partial

https://github.com/StarcounterApps/People/blob/develop/src/People/wwwroot/People/viewmodels/PersonPage.html#L82

https://github.com/StarcounterApps/People/blob/develop/src/People/ViewModels/PersonPage.json.cs#L220

https://github.com/Starcounter/starcounter-include/issues/29

**Comment by tomalec** [comment] 2017-09-12 18:25
Could we close this issue? As for me, it's won't fix.

**Comment by alshakero** [comment] 2017-09-13 07:25
I'm only referring people to this issue because it has good explanation/answer. Maybe some blog post or any write-up anywhere would do.

**Comment by tomalec** [comment] 2017-10-10 12:43
See https://starcounter.io/starcounter-include-non-namespaced-partial-view-models/ for more detailed descriptions.

I'll close it as won't fix.

**Closed as completed by tomalec** 2017-10-10 12:43 UTC
Labels: wontfix

**Comment by alshakero** [comment] 2017-10-10 12:57
Wow, awesome job!

**Comment by alshakero** [comment] 2017-10-11 12:53
@tomalec [the snippet](https://starcounter.io/starcounter-include-non-namespaced-partial-view-models/) is missing `is="imported-template"`, right? (ctrl+f "Naturally, you will need to update all yo").

**Comment by tomalec** [comment] 2017-10-12 07:06
done, thx
