### ISSUE TITLE
⏰ It calls `partialChanged` in constructor

### ISSUE THREAD

**Issue by alshakero** [Starcounter/starcounter-include#71] opened 2017-12-19 11:31 UTC
It calls `partialChanged` in the constructor when `this.template` is `undefined`, rendering the call useless and a white page app.

See this line https://github.com/Starcounter/starcounter-include/blob/10f4e393661441f09c52effad73588a79587ff00/starcounter-include.html#L166

Which calls this, which returns, because`this.template` is undefined:
https://github.com/Starcounter/starcounter-include/blob/10f4e393661441f09c52effad73588a79587ff00/starcounter-include.html#L186-L208

Moving this line https://github.com/Starcounter/starcounter-include/blob/10f4e393661441f09c52effad73588a79587ff00/starcounter-include.html#L166 to `connectedCallback` after `this.stampImportedTemplate();` fixes the issue.

Before I explain reproduction, there is a chance that you could save yourself some time by just looking at the code and decide if my fix makes sense without any repro.

---

### If you want to reproduce this, you'll need to:

1. Clone [KitchenSink#sc-i-bug](https://github.com/Starcounter/KitchenSink/tree/sc-i-bug).
2. Clone [StarcounterClientFiles#master-2.4](https://github.com/Starcounter/StarcounterClientFiles/tree/master-2.4)
3. Build & Run StarcounterClientFiles **first**.
4. Build & Run KitchenSink. 

Go to http://localhost:8080/KitchenSink, you should see a white page ~every other refresh.

**NOTE: if you want to experiment with fixing the bug, make sure to edit files in `StarcounterClientFiles\src\StarcounterClientFiles\wwwroot\sys` not in Program Files\Starcounter\...**

**Comment by tomalec** [comment] 2017-12-19 12:13
Could you isolate it to jsbin?

In general, I'd say we have a little mess in a lifecycle of this element. Probably due to legacy apps and frameworks support, ad hoc quick-fixes, lack of tests and JSDocs. I'd prefer to do urgent changes more consciously (as almost all changes to `sc-include` are urgent recently) add some tests for every fix and so on.

What is the scenario? are we setting partial before the element is upgraded and it's not being stamped because of that?

**Comment by alshakero** [comment] 2017-12-19 12:36
> Could you isolate it to jsbin?

I tried and it's really not easy to have the whole stack replicated. Requesting to `/sc/...` is hardcoded and I can't overcome that on jsbin.

> What is the scenario? are we setting partial before the element is upgraded and it's not being stamped because of that?

Well `createComponent` is called in the constructor, and the constructor is obviously called before `connectedCallback`, `connectedCallback` calls `stampImportedTemplate`. 

`stampImportedTemplate` is what gives `this.template` a value, a value that is needed in `createComponent`, because it calls `partialChanged`.

**Comment by tomalec** [comment] 2017-12-19 14:14
> `connectedCallback` is what gives `this.template` a value, **a value that is needed in `stampImportedTemplate`**.

`stampImportedTemplate` is the method that gives `template` a value, and does not need it.
https://github.com/Starcounter/starcounter-include/blob/10f4e393661441f09c52effad73588a79587ff00/starcounter-include.html#L77

**Comment by tomalec** [comment] 2017-12-19 14:22
Speaking of `partialChanged`

I would say the problem is that `href` is not build and fetched once stamping imported template due to https://github.com/Starcounter/starcounter-include/commit/343a7a0b1169d1cdb1d66c82bcedc729eb83a3a7#diff-311b0326287a7afd52520e5505a3f7feL56

@warpech  Could you elaborate why it was a problem and was removed?

**Comment by warpech** [comment] 2017-12-19 14:48
I removed the line https://github.com/Starcounter/starcounter-include/blob/90e303880a46a7e8dcbd930913e328cc0b026a03/starcounter-include.html#L79 because it looked redundant given that the same action happens in https://github.com/Starcounter/starcounter-include/blob/90e303880a46a7e8dcbd930913e328cc0b026a03/starcounter-include.html#L206. 

After the removal, none of the tests failed.

If this is the reason for the problem, please restore it and add tests.

**Comment by alshakero** [comment] 2017-12-19 15:18
> stampImportedTemplate is the method that gives the template a value, and does not need it.

Sorry, my bad, I just failed to describe what I thought. And I still can't say something clear about it. Here is what I think is happening:

![image](https://user-images.githubusercontent.com/17054134/34163832-25160f5a-e4d8-11e7-9062-99a022f02c5d.png)

And here is what I think should happen instead:
![image](https://user-images.githubusercontent.com/17054134/34164172-2ad77eaa-e4d9-11e7-81cc-f406d9cbc349.png)

**Comment by warpech** [comment] 2017-12-19 17:28
I have pushed a workaround here: https://github.com/Starcounter/StarcounterClientFiles/tree/workaround-for-starcounter-include-71

**Comment by tomalec** [comment] 2017-12-27 17:50
I think I've isolated the problem, here is the bunch of test for it https://github.com/Starcounter/starcounter-include/pull/74

I have also prepared a better fix for this issue. But, I'll wait for the PR above to make reviews and cleaning my code easier.

**Comment by warpech** [comment] 2017-12-29 12:42
Great to hear about the isolation! Any progress with the fix?

**Comment by tomalec** [comment] 2017-12-29 14:55
It's ready, I just try to provide it in digestive/reviewable form, divided into separate PRs (https://github.com/Starcounter/starcounter-include/pull/74, https://github.com/Starcounter/starcounter-include/pull/77). Today I'll push the PR with a fix. However, `sc-include` still needs some cleanup, tests, and love ;)

**Comment by tomalec** [comment] 2018-01-06 10:35
Fixed and released in `2.4.0.4448` https://github.com/Starcounter/level1/pull/4435

**Closed as completed by tomalec** 2018-01-06 10:35 UTC

**Comment by warpech** [comment] 2018-01-10 17:27
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/starcounter-include/releases/tag/4.1.0
- included in a Finished release of SCF https://github.com/Starcounter/StarcounterClientFiles/releases/tag/2.1.0
