### ISSUE TITLE
Deprecate `partial` attribute in favor of `view-model`

### ISSUE THREAD

**Issue by tomalec** [Starcounter/starcounter-include#38] opened 2017-06-23 16:56 UTC
As part of renaming effort https://github.com/Starcounter/TechComm/issues/286 we made a `view-model` alias for `partial`.

I think it's the time to deprecate the old one, to stop maintaining both sooner.

We could just `console.warn` a message any time the property/attribute is set.

@Starcounter/sc-blendingtf , @warpech What App Architecture TF thinks about that?

**Comment by tomalec** [comment] 2017-06-28 12:50
This would be needed for refactoring of `sc-include` done for https://github.com/Starcounter/RebelsLounge/issues/78

**Comment by warpech** [comment] 2017-06-28 12:59
I will discuss this on the next App Arch TF meeting for a definitive answer

**Comment by tomalec** [comment] 2017-06-28 13:02
Ok, for now I will just change the code so `partial` will be alias of `view-model` not vice-versa. So it would be fairly easy to add warning and remove it in future.

**Comment by tomalec** [comment] 2017-07-25 19:39
@warpech Have App Arch TF discussed this issue?

**Comment by warpech** [comment] 2017-07-26 09:33
Nope, there were other topics that consumed our attention (mostly Session).

I think that deprecation message is ok, but we should not remove the `partial` attribute in the foreseeable future. 

First potential time window to remove it is when we do the Polymer 2.0 upgrade.

**Comment by tomalec** [comment] 2017-08-02 10:56
We will use `view-model` as main attribute, `partial` as an alias, and throw a warning whenever is set.

**Comment by warpech** [comment] 2017-09-14 16:04
Any thoughts about how this relates to the new JSON structure presented here: https://github.com/Starcounter/RebelsLounge/issues/97?

It seems to me that we actually don't want a `view-model` attribute but a `view` attribute here.

Related: https://github.com/Starcounter/RebelsLounge/issues/85

**Comment by tomalec** [comment] 2017-09-27 09:45
We would like to ship it in 2.4

**Comment by warpech** [comment] 2017-12-06 11:13
Any new thoughts on this? It would be good to decide and implement this in an early release of 4.0.0-rc, before devs started upgrading their apps.

**Comment by tomalec** [comment] 2017-12-07 19:37
good point, but I've just released `4.0.0`, should I delete the tag and set it to `4.0.0-rc.1`?

If we still want to provide silky smooth transition and support both, but throw a warning for `partial`, I would not consider it a breaking API change and we could release it later as 4.0.1, just kindly asking dev in the console to do simple search&replace.

If we drop that approach and are fine with breaking change, it would be way faster to make, and then I would release it with `4.0.0`

**Comment by tomalec** [comment] 2017-12-07 19:40
Speaking of hybrid views, the ones with `<starcounter view-model="..` are actually already hybrid. As they will work with `2.4` and they are working already in `2.3`. Just are not so popular yet.

**Comment by warpech** [comment] 2017-12-07 22:50
If it was not an obstacle to publish 4.0.0 then we can as well keep it until 5.0.0, maybe with Starcounter 2.5.

What's your opinion on https://github.com/Starcounter/starcounter-include/issues/38#issuecomment-329529990?

**Comment by tomalec** [comment] 2017-12-08 11:48
Speaking of https://github.com/Starcounter/RebelsLounge/issues/97, this name may or may not be a good fit.

Regarding `view-model` and `model`. We also had a discussion that using `model` attr to attach a partial view-model and a property `.model` attached to a stamped node would allow to nest `<starcounter-include>`s without a need for Polymer, with a tiny risk of circular reference (which may no longer be applicable as we dropped non-namespaced partials).
I think we may consider `model` attribute once we will change the structure as in Starcounter/RebelsLounge/issues/97.

I'm more keen to support `view-model` and `model` as an alias rather than `partial` and `view-model`.

Especially that it would help us to forget about https://github.com/Starcounter/TechComm/issues/286

**Comment by warpech** [comment] 2017-12-11 15:02
Can we then keep the support for both attributes `partial` and `view-model` until https://github.com/Starcounter/RebelsLounge/issues/97 is decided?

Still, I would like to make sure we promote `view-model="..."` rather than `partial="..."`

1. @Mackiovello I can't find a blog post that announces renaming the `partial` attribute to `view-model` and I think there should be one. Could you please write a blog post about it and add info since what version of Starcounter the new attribute is available?
2. @Mackiovello could you check if docs for 2.3.1 and 2.4 use `view-model="..."`, not `partial="..."`?
3. @PatrykSzwer could you please make PRs in Web Platfrom Team apps to use `view-model="..."`, not `partial="..."`?
4. @Mihaiii you please make PRs in the Apps Team apps to use `view-model="..."`, not `partial="..."`?

**Comment by ErlendLandro** [comment] 2017-12-11 15:36
The docs are updated to use `view-model="..."`.

Blog post is published here: https://starcounter.io/partial-attribute-starcounter-include-component-renamed-view-model/

**Comment by PatrykSzwer** [comment] 2017-12-13 13:09
>@PatrykSzwer could you please make PRs in Web Platfrom Team apps to use view-model="...", not partial="..."?

I've made PRs for our apps.

**Comment by tomalec** [comment] 2018-02-21 20:56
@alshakero feel free to take it :)

**Comment by warpech** [comment] 2018-02-22 10:47
To clarify, the issue is not to remove `partial` property. It is just to have `viewModel` as the default one, `partial` as the aliased one, and make a warning when `partial` is used.

**Comment by alshakero** [comment] 2018-02-23 11:23
BTW. I think we should postpone this. Because it's actually slower to deprecate an attrib. WDYT?

**Comment by warpech** [comment] 2018-02-23 12:30
Isn't it enough to do something like https://github.com/Starcounter/starcounter-include/blob/a1731a7d9c351d45b26a023a709de9f248d3c38c/starcounter-include.html#L107-L109 

And change few `if`s?

You can even have a test for it quite easily: https://github.com/Starcounter/starcounter-include/blob/a8afd0928c1a82ec8202d4b26ecd64ce912370f6/test/composition/default-starcounter-composition.html#L77-L80

**Comment by alshakero** [comment] 2018-02-23 13:09
Sorry I misexplained. I mean it's slower performance-wise to check for `parital` everytime. Implementation should be easy.

**Comment by warpech** [comment] 2018-02-23 14:45
The point of deprecation is that the app developers should upgrade to use `view-model` instead of `partial`.

**Comment by alshakero** [comment] 2018-03-05 15:28
Closing as done and released in https://github.com/Starcounter/starcounter-include/releases/tag/5.0.0

**Closed as completed by alshakero** 2018-03-05 15:28 UTC
Labels: 2.4.x, web, web-blending
