### ISSUE TITLE
Replacing app's response without MasterPage not always works

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter-include#34] opened 2017-06-01 11:52 UTC
I just ran an experiment that tries to remove the need for `MasterPage` from a Starcounter app (Images). The experiment actually works ok if only the Images app is running. But when Images + Website (`develop`) is running, it doesn't work well.

1. Build and run: Images `experiment-remove-MasterPage` branch
1. Build and run: Website `develop` branch
2. Go to http://localhost:8080/images
3. Click on "Add image or video"
4. Click on "Cancel"

## Expected

You should see the images list again.

## Actual

You still see the image editing form.

## Screenshot

![bug](https://cloud.githubusercontent.com/assets/566463/26678581/6d35ec38-46d1-11e7-93be-402b2e35bbde.gif)

**Comment by tomalec** [comment] 2017-06-06 00:27
Seems to be caused by wrapping https://github.com/StarcounterApps/Website/issues/105

**Comment by warpech** [comment] 2017-06-06 08:05
I can reproduce this problem with Starcounter 2.3.1.6523, which includes https://github.com/Starcounter/Home/issues/89.

I don't think there is any magic in Website. The problem is also reproducible if you use Launcher + Images, so I think it must be something in `starcounter-include`. 

@alshakero maybe you could help with the investigation?

**Comment by warpech** [comment] 2017-06-06 12:41
Strangely enough, this problem is not reproducible in https://github.com/StarcounterApps/Website/pull/107. 

I think that:

1. @tomalec is right that complexity of Website and Launcher contributes to the problem
2. Reducing the complexity of Website fixes this instance of the problem, but still I think that the problem reproducible with https://github.com/StarcounterApps/Website/commit/abb16901f032bea08d7b889d7bb60e133b9c56f7 and https://github.com/StarcounterAppsFreezer/Launcher/commit/58ca8097d85fcd570578140f022eff7799ae0102 should be fixed.

**Comment by tomalec** [comment] 2017-06-06 17:47
Could we please setup a HO call on that?

That's related to the fact that `starcounter-include` do not expect single scope of merged partial view-model to be changed. I may change it so it will observe any change of `viewModel.*` and refresh/rebuild merged URI for HTML => reload the partial. But this would be definitely not desired behavior for non-namespaced partials (see https://github.com/Starcounter/starcounter-include/issues/29, https://github.com/Starcounter/Home/issues/89 - I hope now you can see why I called it a hack that was hiding a problem).
Then `viewModel.*` is simply any property of app's view-model.

**Comment by tomalec** [comment] 2017-06-14 14:08
![20170614_160509](https://user-images.githubusercontent.com/17435/27136490-bef83b58-511b-11e7-9f3b-cc775831d615.jpg)

**Comment by tomalec** [comment] 2017-06-14 14:21
As decided with @warpech on f2f meeting, until we have namespaced partial view-model on root, we will provide explicit flag - attribute for `sc-include` that switches to non-namespaced mode, so we could listen to individual partials changes (within merged).

**Comment by tomalec** [comment] 2017-06-28 14:14
@warpech one more question what should exactly happen when you reload the individual partial in merged one? I'm asking about markup reload and data binding.

| # | Scoped | What happened?                                           | Should entire merged HTML be reloaded? | Should model be attached instantly? |
|---|--------|----------------------------------------------------------|----------------------------------------|-------------------------------------|
| 1 | ✓      | `{op: 'replace', path: 'partial', value: {...}}`         | ✓                                      | once loaded                         |
| 2 | ✓      | `{op: 'replace', path: 'partial.Html', value: {...}}`    | ✓                                      | once loaded                         |
| 3 | ✗      | `{op: 'replace', path: 'partial.Html', value: {...}}`    | ✓                                      | once loaded                         |
| 4 | ✓      | `{op: 'replace', path: 'partial.Launcher.LayoutInfo.Html', value: {...}}`    | ✓                                      | once loaded                         |
| 5 | ✓      | `{op: 'replace', path: 'partial.foo.bar', value: {...}}` | ✗                                      | ✓                                   |
| 6 | ✓      | `{op: 'replace', path: 'partial.foo.Html', value: {...}}` | ✓                                      | once loaded                                   |
| 7 | ✓      | `{op: 'replace', path: 'partial.foo', value: {...}}` | ?                                      | ?                                   |
| 7.1 | ✓      | `{op: 'replace', path: 'partial.foo', value: {...no Html property and there was none before...}}` | ?                                      | ?                                   |
| 7.2 | ✓      | `{op: 'replace', path: 'partial.foo', value: {...no Html property but there was one before...}}` | ?                                      | ?                                   |
| 7.3 | ✓      | `{op: 'replace', path: 'partial.foo', value: {...same Html property as it was before...}}` | ?                                      | ?                                   |
| 7.4 | ✓      | `{op: 'replace', path: 'partial.foo', value: {...different Html property as it was before...}}` | ?                                      | ?                                   |
| 8 | ✓      | `{op: 'remove', path: 'partial.foo'}` | ?                                      | ?                                   |
| 9 | ✗      | `{op: 'replace', path: 'partial', value: {...}}` | ✓                                      | once loaded                                   |


See question marks. I'm not even sure we should bother about 7.x cases.


On one hand I'd say
> If you change **your** entire partial, regardless if it's same URL or new one, you mean to reload. Otherwise you would `replace` all props. Then speaking of siblings, if you ask to reload a partial, as siblings are attached by additional layer, we should reload them to.

> If you change you partial, potentially there is a new HTML => new composition, that's why other siblings should flicker anyways

However it heavily limits use cases where: 
 - app dev would like to switch just object data, keeping same tamplate
 - app dev would like to switch templates but use the same Shadow DOM composition to distribute it withou flickering

Once again we are back on view-models structure issue https://github.com/Starcounter/RebelsLounge/issues/97, with separation of `{View:.., Data:...}` it would be straight forward, plus removal of non-namespaced partials would simplify it even more.


I'd consider those issues blocking further development of `sc-include` -  https://github.com/Starcounter/RebelsLounge/issues/78, and mark as P/High

**Comment by warpech** [comment] 2017-06-28 14:48
Instead of `partial.Launcher.LayoutInfo.Html` should be `partial.CompositionProvider.MergedHtml`, right?

I think that 7, 7.x and 8 are:

- the same as 5, if none of the `Html` values change
- the same as 6, if any of the `Html` values change

**Comment by tomalec** [comment] 2017-06-28 15:02
>Instead of partial.Launcher.LayoutInfo.Html should be partial.CompositionProvider.MergedHtml, right?

Currently it's `partial.Launcher.LayoutInfo.Html` https://github.com/Starcounter/starcounter-include/blob/8811885406f767865461476100b409994f102abf/starcounter-include.html
Is Composition provider providing also MergedHtml? I thought currently nobody does so.
So in general would remove this legacy.


> I think that 7, 7.x and 8 are:
>- the same as 5, if none of the `Html` values change
>- the same as 6, if any of the `Html` values change

That means, we will be additionally re-calculating `MergedHtml` on every add(replace)/remove of any property of namespaced view model or Starcounter metadata (`_ver#s`, etc), just to check whether to postpone or not model application. As I don't think caching just `Html` properties is a good idea.

Also this introduces inconsistent behavior with non-namespaced, but what's more important does not allow user to forcefully reload same partial.

**Comment by warpech** [comment] 2017-06-29 15:04
https://github.com/Starcounter/starcounter-include/blob/8811885406f767865461476100b409994f102abf/starcounter-include.html does not contain `partial.Launcher.LayoutInfo.Html`. It contains `partial.LauncherLayoutInfo.Html`, which worked in the past. Since https://github.com/Starcounter/starcounter-include/commit/82b5b86e4951ac259186e9acff1fcab3e78ee971, `starcounter-include` supports `partial.CompositionProvider.Html` for the reasons explained in https://github.com/Starcounter/starcounter-include/issues/30.

Before we made https://github.com/Starcounter/starcounter-include/commit/82b5b86e4951ac259186e9acff1fcab3e78ee971, CompositionProvider had to fake that it is called "LauncherLayoutInfo" using `RunWithinApplication`, but that was changed in https://github.com/StarcounterApps/CompositionProvider/commit/2e29fa6f9ea2aa5af93c83ad166c1e6b6ba48703. Since this commit, CompositionProvider's output appears in namespace  "CompositionProvider". Soon it will appear in namespace "CompositionProvider_0"

> I thought currently nobody does so. So in general would remove this legacy.

I agree, it can be removed now.

Regarding 7, 7.x and 8, do you have any alternative ideas?

> Also this introduces inconsistent behavior with non-namespaced, but what's more important does not allow user to forcefully reload same partial.

Non-namespaced will be removed https://github.com/Starcounter/starcounter-include/issues/29

**Comment by tomalec** [comment] 2017-06-30 11:12
Cool, so I will remove `MergedHtml` and `LauncherLayoutInfo` related code, ok?

----

> Non-namespaced **will** be removed #29

We plan to deprecate it, but probably we will have to support it for some time. W
e agree, with specific flag we agreed on F2F meeting https://github.com/Starcounter/starcounter-include/issues/34#issuecomment-308446635, I'm now trying to implement. For which I need this defined behavior for.


----

> Regarding 7, 7.x and 8, do you have any alternative ideas?

https://github.com/Starcounter/RebelsLounge/issues/97 II.

**Comment by tomalec** [comment] 2017-08-02 10:22
Closing as done. PRs above fixed OP, the partial reloading in respect of HTML change should be tracked at https://github.com/Starcounter/RebelsLounge/issues/97

**Closed as completed by tomalec** 2017-08-02 10:22 UTC
Labels: blocking
