### ISSUE TITLE
supress warnings

### ISSUE THREAD

**Issue by malx122** [Starcounter/starcounter-include#5] opened 2015-10-23 07:25 UTC
Right now, starcounter-include give a lot of warnings when used dynamically (data model for the include is null until/if ever it should be shown). Not very good...

partial.Html for <starcounter-include>​…​</starcounter-include>​ ​ is missing.
partial.PartialId for <starcounter-include>​…​</starcounter-include>​ is missing.

**Comment by warpech** [comment] 2015-10-23 09:32
This should be fixed by https://github.com/Starcounter/Starcounter/issues/2902 & https://github.com/Starcounter/Starcounter/issues/2690

**Comment by malx122** [comment] 2015-10-23 10:45
Nope, not at all!
This is for a "on purpose" null object from the server until used, not for a request with partials.

**Comment by dan31** [comment] 2015-11-02 10:56
Bump.

**Comment by warpech** [comment] 2015-11-05 21:49
@malx122 it seems I am not able to reproduce it locally. Could you please create a minimum app that reproduces this problem? 

Or try reproducing it with one of StarcounterSamples. I tried in People, by replacing a partial handler with the following code:

``` cs
            Handle.GET<string>("/people/partials/persons/{?}", (string id) => {
                return Db.Scope<PersonPage>(() => {
                    PersonPage page = new PersonPage() {
                        Html = "/People/viewmodels/PersonPage.html"
                    };

                    //page.RefreshPerson(id);

                    return page;
                });
            });
```

And then going to http://localhost:8080/people/persons/add. It loads without the warnings that you mentioned (tested with Launcher turned on and off)

**Comment by tomalec** [comment] 2016-05-06 15:52
I'm closing this as old and non-reproducible. @malx122 Please reopen, once you will encounter it once again.

**Closed as completed by tomalec** 2016-05-06 15:52 UTC
